In [1]:
import numpy as np
import pandas as pd

In [2]:
pip install youtube-comment-scraper-python

Collecting youtube-comment-scraper-pythonNote: you may need to restart the kernel to use updated packages.

  Downloading youtube-comment-scraper-python-1.0.0.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: requests in c:\users\sharn\anaconda3\lib\site-packages (from youtube-comment-scraper-python) (2.28.1)
Collecting bot-studio
  Downloading bot_studio-1.4.0.tar.gz (55.4 MB)
     ---------------------------------------- 55.4/55.4 MB 2.4 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: tqdm in c:\users\sharn\anaconda3\lib\site-packages (from bot-studio->youtube-comment-scraper-python) (4.64.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\sharn\anaconda3\lib\site-packages (from requests->youtube-comment-scraper-python) (1.26.11)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\sharn\anaconda3\lib\site-packages (from requests->youtube-comment-scraper-python) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sharn\anaconda3\lib\site-packages (from requests->youtube-comment-scraper-python) (2022.9.14)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sharn\anaconda3\lib\site-packages (from requests->youtube-comment-scraper-python) (3.3)
Requirement already satisfied: colorama in c:\users\sharn\anaconda3\lib\site-packages (from tqdm->bot-studio->youtube-comment-scraper-python) (0.4.5)
Building wheels for collected packages: youtube-comment-scraper-python, bot-studio
  Building wheel for youtube-comment-scraper-python (setup.py): started
  Building wheel for youtube-comment-scraper-python (setup.py): finished with status 'done'
  Created wheel for youtube-comment-scraper-python: filename=youtube_comment_scraper_python-1.0.0-py3-none-any.whl size=2482 sha256=c29f8548ec1e991baa17f7d799c50cbef37e461a4ca7af4d0513040d3c6b1066
  Stored in directory: c:\users\sharn\appdata\local\pip\cache\wheels\86\31\e4\ddf67abcab05e0648915e34601631657c1c9c6b60ce67fc8f9
  Building wheel for bot-studio (setup.py): started
  Building wheel for bot-studio (setup.py): finished with status 'done'
  Created wheel for bot-studio: filename=bot_studio-1.4.0-py3-none-any.whl size=55391266 sha256=3f320e46aee57f58070403b880cd42ea7655ad34c1666ed9856d8c13d3f1b447
  Stored in directory: c:\users\sharn\appdata\local\pip\cache\wheels\34\bd\42\d1df11be0be60bb4272430ce77f26516b187fc374a607448b2
Successfully built youtube-comment-scraper-python bot-studio
Installing collected packages: bot-studio, youtube-comment-scraper-python
Successfully installed bot-studio-1.4.0 youtube-comment-scraper-python-1.0.0

In [3]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline
import os

# Import functions for data preprocessing & data preparation
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import resample
from sklearn.feature_extraction.text import CountVectorizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer

from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer, LancasterStemmer
from nltk.stem.snowball import SnowballStemmer
from nltk.corpus import stopwords
from nltk.corpus import wordnet
import string
from string import punctuation
import nltk
import re

In [6]:
data = pd.read_csv("C:/Users/sharn/Desktop/DM/ecocrisis.csv")
data.columns
data

                                  Transcript
0    all that advice depends on people being
1    able to hold on to their jobs after all
2    unfortunately that's not a guarantee in
3          this market across Silicon Valley
4   companies are now downsizing Tech giants
..                                       ...
78      plans to cut their expenses job cuts
79  across the industry could intensify Leon
80     world is one is now available in your
81  country download the app now and get all
82              the news updates on the move

[83 rows x 1 columns]

In [7]:
nltk.download('vader_lexicon')
sentiments = SentimentIntensityAnalyzer()
data["Positive"] = [sentiments.polarity_scores(i)["pos"] for i in data["Transcript"]]
data["Negative"] = [sentiments.polarity_scores(i)["neg"] for i in data["Transcript"]]
data["Neutral"] = [sentiments.polarity_scores(i)["neu"] for i in data["Transcript"]]
data['Compound'] = [sentiments.polarity_scores(i)["compound"] for i in data["Transcript"]]
score = data["Compound"].values
sentiment = []
for i in score:
    if i >= 0.05 :
        sentiment.append('Positive')
    elif i <= -0.05 :
        sentiment.append('Negative')
    else:
        sentiment.append('Neutral')
data["Sentiment"] = sentiment
data

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\sharn\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

,Transcript,Positive,Negative,Neutral,Compound,Sentiment
0,all that advice depends on people being,0.0,0.000,1.000,0.0000,Neutral
1,able to hold on to their jobs after all,0.0,0.000,1.000,0.0000,Neutral
2,unfortunately that's not a guarantee in,0.0,0.580,0.420,-0.4836,Negative
3,this market across Silicon Valley,0.0,0.000,1.000,0.0000,Neutral
4,companies are now downsizing Tech giants,0.0,0.000,1.000,0.0000,Neutral
...,...,...,...,...,...,...
78,plans to cut their expenses job cuts,0.0,0.462,0.538,-0.5106,Negative
79,across the industry could intensify Leon,0.0,0.000,1.000,0.0000,Neutral
80,world is one is now available in your,0.0,0.000,1.000,0.0000,Neutral
81,country download the app now and get all,0.0,0.000,1.000,0.0000,Neutral
82,the news updates on the move,0.0,0.000,1.000,0.0000,Neutral

In [8]:
data1=data.drop(['Positive','Negative','Neutral','Compound'],axis=1)
data1

                                  Transcript Sentiment
0    all that advice depends on people being   Neutral
1    able to hold on to their jobs after all   Neutral
2    unfortunately that's not a guarantee in  Negative
3          this market across Silicon Valley   Neutral
4   companies are now downsizing Tech giants   Neutral
..                                       ...       ...
78      plans to cut their expenses job cuts  Negative
79  across the industry could intensify Leon   Neutral
80     world is one is now available in your   Neutral
81  country download the app now and get all   Neutral
82              the news updates on the move   Neutral

[83 rows x 2 columns]

In [9]:
count1=0
count2=0
count3=0
for i in score:
    
    if i>=0.05:
        count1+=1
    elif i <= -0.05:
        count2+=1
    else:
        count3+=1

positive_per=count1/100*100
negative_per=count2/100*100
neutral_per=count3/100*100
print("Positive percentage:",positive_per,"%")
print("Negative percentage:",negative_per,"%")
print("Neutral percentage:",neutral_per,"%")

Positive percentage: 12.0 %
Negative percentage: 20.0 %
Neutral percentage: 51.0 %

In [11]:
if positive_per >= (neutral_per + negative_per + 10) :
    print("Global economic crisis hits the tech sector by",positive_per,"%")

elif negative_per>= (neutral_per + positive_per + 10):
    print("Global economic crisis hits the tech sector by",negative_per,"%")

else :
    print("Global economic crisis hits the tech sector by",negative_per,"%")

Global economic crisis hits the tech sector by 20.0 %